CREATE TABLE `CDS` (
                       `CD_ID` bigint NOT NULL,
                       PRIMARY KEY (`CD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `DBS` (
                       `DB_ID` bigint NOT NULL,
                       `DESC` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                       `DB_LOCATION_URI` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                       `NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                       `OWNER_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                       `OWNER_TYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                       PRIMARY KEY (`DB_ID`),
                       UNIQUE KEY `UNIQUE_DATABASE` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DATABASE_PARAMS` (
                                   `DB_ID` bigint NOT NULL,
                                   `PARAM_KEY` varchar(180) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                                   `PARAM_VALUE` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                   PRIMARY KEY (`DB_ID`,`PARAM_KEY`),
                                   KEY `DATABASE_PARAMS_N49` (`DB_ID`),
                                   CONSTRAINT `DATABASE_PARAMS_FK1` FOREIGN KEY (`DB_ID`) REFERENCES `DBS` (`DB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;




CREATE TABLE `GLOBAL_PRIVS` (
                                `USER_GRANT_ID` bigint NOT NULL,
                                `CREATE_TIME` int NOT NULL,
                                `GRANT_OPTION` smallint NOT NULL,
                                `GRANTOR` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                `GRANTOR_TYPE` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                `PRINCIPAL_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                `PRINCIPAL_TYPE` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                `USER_PRIV` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                PRIMARY KEY (`USER_GRANT_ID`),
                                UNIQUE KEY `GLOBALPRIVILEGEINDEX` (`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`USER_PRIV`,`GRANTOR`,`GRANTOR_TYPE`),
                                CONSTRAINT `GLOBAL_PRIVS_chk_1` CHECK ((`GRANT_OPTION` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PART_COL_STATS` (
                                  `CS_ID` bigint NOT NULL,
                                  `AVG_COL_LEN` double DEFAULT NULL,
                                  `COLUMN_NAME` varchar(767) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                                  `COLUMN_TYPE` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                                  `DB_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                                  `BIG_DECIMAL_HIGH_VALUE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                  `BIG_DECIMAL_LOW_VALUE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                                  `DOUBLE_HIGH_VALUE` double DEFAULT NULL,
                                  `DOUBLE_LOW_VALUE` double DEFAULT NULL,
                                  `LAST_ANALYZED` bigint NOT NULL,
                                  `LONG_HIGH_VALUE` bigint DEFAULT NULL,
                                  `LONG_LOW_VALUE` bigint DEFAULT NULL,
                                  `MAX_COL_LEN` bigint DEFAULT NULL,
                                  `NUM_DISTINCTS` bigint DEFAULT NULL,
                                  `NUM_FALSES` bigint DEFAULT NULL,
                                  `NUM_NULLS` bigint NOT NULL,
                                  `NUM_TRUES` bigint DEFAULT NULL,
                                  `PART_ID` bigint DEFAULT NULL,
                                  `PARTITION_NAME` varchar(767) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                                  `TABLE_NAME` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                                  PRIMARY KEY (`CS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `ROLES` (
                         `ROLE_ID` bigint NOT NULL,
                         `CREATE_TIME` int NOT NULL,
                         `OWNER_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                         `ROLE_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                         PRIMARY KEY (`ROLE_ID`),
                         UNIQUE KEY `ROLEENTITYINDEX` (`ROLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SDS` (
                       `SD_ID` bigint NOT NULL,
                       `CD_ID` bigint DEFAULT NULL,
                       `INPUT_FORMAT` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                       `IS_COMPRESSED` bit(1) NOT NULL,
                       `IS_STOREDASSUBDIRECTORIES` bit(1) NOT NULL,
                       `LOCATION` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                       `NUM_BUCKETS` int NOT NULL,
                       `OUTPUT_FORMAT` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
                       `SERDE_ID` bigint DEFAULT NULL,
                       PRIMARY KEY (`SD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `SEQUENCE_TABLE` (
                                  `SEQUENCE_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                                  `NEXT_VAL` bigint NOT NULL,
                                  PRIMARY KEY (`SEQUENCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `SKEWED_STRING_LIST` (
                                      `STRING_LIST_ID` bigint NOT NULL,
                                      PRIMARY KEY (`STRING_LIST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `VERSION` (
                           `VER_ID` bigint NOT NULL,
                           `SCHEMA_VERSION` varchar(127) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                           `VERSION_COMMENT` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
                           PRIMARY KEY (`VER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `TBLS`
(
    `TBL_ID` BIGINT NOT NULL,
    `CREATE_TIME` INTEGER NOT NULL,
    `DB_ID` BIGINT NULL,
    `LAST_ACCESS_TIME` INTEGER NOT NULL,
    `OWNER` VARCHAR(767) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    `RETENTION` INTEGER NOT NULL,
    `IS_REWRITE_ENABLED` TINYINT(1) NOT NULL,
    `SD_ID` BIGINT NULL,
    `TBL_NAME` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    `TBL_TYPE` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    `VIEW_EXPANDED_TEXT` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `VIEW_ORIGINAL_TEXT` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    CONSTRAINT `TBLS_PK` PRIMARY KEY (`TBL_ID`)
) ENGINE=InnoDB;


CREATE TABLE `SERDE_PARAMS`
(
    `SERDE_ID` BIGINT NOT NULL,
    `PARAM_KEY` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `PARAM_VALUE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    CONSTRAINT `SERDE_PARAMS_PK` PRIMARY KEY (`SERDE_ID`,`PARAM_KEY`)
) ENGINE=InnoDB;


CREATE TABLE `TABLE_PARAMS`
(
    `TBL_ID` BIGINT NOT NULL,
    `PARAM_KEY` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `PARAM_VALUE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    CONSTRAINT `TABLE_PARAMS_PK` PRIMARY KEY (`TBL_ID`,`PARAM_KEY`)
) ENGINE=InnoDB;

CREATE TABLE `COLUMNS_V2`
(
    `CD_ID` BIGINT NOT NULL,
    `COMMENT` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
    `COLUMN_NAME` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `TYPE_NAME` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `INTEGER_IDX` INTEGER NOT NULL,
    CONSTRAINT `COLUMNS_PK` PRIMARY KEY (`CD_ID`,`COLUMN_NAME`)
) ENGINE=InnoDB;



CREATE TABLE `SD_PARAMS`
(
    `SD_ID` BIGINT NOT NULL,
    `PARAM_KEY` VARCHAR(256) BINARY NOT NULL,
    `PARAM_VALUE` MEDIUMBLOB NULL,
    CONSTRAINT `SD_PARAMS_PK` PRIMARY KEY (`SD_ID`,`PARAM_KEY`)
) ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS `BUCKETING_COLS` (
                                                `SD_ID` bigint(20) NOT NULL,
    `BUCKET_COL_NAME` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`SD_ID`,`INTEGER_IDX`),
    KEY `BUCKETING_COLS_N49` (`SD_ID`),
    CONSTRAINT `BUCKETING_COLS_FK1` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `CDS` (
                                     `CD_ID` bigint(20) NOT NULL,
    PRIMARY KEY (`CD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `COLUMNS_V2` (
                                            `CD_ID` bigint(20) NOT NULL,
    `COMMENT` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `COLUMN_NAME` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `TYPE_NAME` varchar(4000) DEFAULT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`CD_ID`,`COLUMN_NAME`),
    KEY `COLUMNS_V2_N49` (`CD_ID`),
    CONSTRAINT `COLUMNS_V2_FK1` FOREIGN KEY (`CD_ID`) REFERENCES `CDS` (`CD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `DATABASE_PARAMS` (
                                                 `DB_ID` bigint(20) NOT NULL,
    `PARAM_KEY` varchar(180) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PARAM_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`DB_ID`,`PARAM_KEY`),
    KEY `DATABASE_PARAMS_N49` (`DB_ID`),
    CONSTRAINT `DATABASE_PARAMS_FK1` FOREIGN KEY (`DB_ID`) REFERENCES `DBS` (`DB_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `DBS` (
                                     `DB_ID` bigint(20) NOT NULL,
    `DESC` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `DB_LOCATION_URI` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `OWNER_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `OWNER_TYPE` varchar(10) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`DB_ID`),
    UNIQUE KEY `UNIQUE_DATABASE` (`NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `DB_PRIVS` (
                                          `DB_GRANT_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `DB_ID` bigint(20) DEFAULT NULL,
    `GRANT_OPTION` smallint(6) NOT NULL,
    `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `DB_PRIV` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`DB_GRANT_ID`),
    UNIQUE KEY `DBPRIVILEGEINDEX` (`DB_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`DB_PRIV`,`GRANTOR`,`GRANTOR_TYPE`),
    KEY `DB_PRIVS_N49` (`DB_ID`),
    CONSTRAINT `DB_PRIVS_FK1` FOREIGN KEY (`DB_ID`) REFERENCES `DBS` (`DB_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `GLOBAL_PRIVS` (
                                              `USER_GRANT_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `GRANT_OPTION` smallint(6) NOT NULL,
    `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `USER_PRIV` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`USER_GRANT_ID`),
    UNIQUE KEY `GLOBALPRIVILEGEINDEX` (`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`USER_PRIV`,`GRANTOR`,`GRANTOR_TYPE`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `IDXS` (
                                      `INDEX_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `DEFERRED_REBUILD` bit(1) NOT NULL,
    `INDEX_HANDLER_CLASS` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `INDEX_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `INDEX_TBL_ID` bigint(20) DEFAULT NULL,
    `LAST_ACCESS_TIME` int(11) NOT NULL,
    `ORIG_TBL_ID` bigint(20) DEFAULT NULL,
    `SD_ID` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`INDEX_ID`),
    UNIQUE KEY `UNIQUEINDEX` (`INDEX_NAME`,`ORIG_TBL_ID`),
    KEY `IDXS_N51` (`SD_ID`),
    KEY `IDXS_N50` (`INDEX_TBL_ID`),
    KEY `IDXS_N49` (`ORIG_TBL_ID`),
    CONSTRAINT `IDXS_FK1` FOREIGN KEY (`ORIG_TBL_ID`) REFERENCES `TBLS` (`TBL_ID`),
    CONSTRAINT `IDXS_FK2` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`),
    CONSTRAINT `IDXS_FK3` FOREIGN KEY (`INDEX_TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `INDEX_PARAMS` (
                                              `INDEX_ID` bigint(20) NOT NULL,
    `PARAM_KEY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PARAM_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`INDEX_ID`,`PARAM_KEY`),
    KEY `INDEX_PARAMS_N49` (`INDEX_ID`),
    CONSTRAINT `INDEX_PARAMS_FK1` FOREIGN KEY (`INDEX_ID`) REFERENCES `IDXS` (`INDEX_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `NUCLEUS_TABLES` (
                                                `CLASS_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `TABLE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `TYPE` varchar(4) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `OWNER` varchar(2) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `VERSION` varchar(20) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `INTERFACE_NAME` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`CLASS_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PARTITIONS` (
                                            `PART_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `LAST_ACCESS_TIME` int(11) NOT NULL,
    `PART_NAME` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `SD_ID` bigint(20) DEFAULT NULL,
    `TBL_ID` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`PART_ID`),
    UNIQUE KEY `UNIQUEPARTITION` (`PART_NAME`,`TBL_ID`),
    KEY `PARTITIONS_N49` (`TBL_ID`),
    KEY `PARTITIONS_N50` (`SD_ID`),
    CONSTRAINT `PARTITIONS_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`),
    CONSTRAINT `PARTITIONS_FK2` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PARTITION_EVENTS` (
                                                  `PART_NAME_ID` bigint(20) NOT NULL,
    `DB_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `EVENT_TIME` bigint(20) NOT NULL,
    `EVENT_TYPE` int(11) NOT NULL,
    `PARTITION_NAME` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TBL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`PART_NAME_ID`),
    KEY `PARTITIONEVENTINDEX` (`PARTITION_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PARTITION_KEYS` (
                                                `TBL_ID` bigint(20) NOT NULL,
    `PKEY_COMMENT` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PKEY_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PKEY_TYPE` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`TBL_ID`,`PKEY_NAME`),
    KEY `PARTITION_KEYS_N49` (`TBL_ID`),
    CONSTRAINT `PARTITION_KEYS_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PARTITION_KEY_VALS` (
                                                    `PART_ID` bigint(20) NOT NULL,
    `PART_KEY_VAL` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`PART_ID`,`INTEGER_IDX`),
    KEY `PARTITION_KEY_VALS_N49` (`PART_ID`),
    CONSTRAINT `PARTITION_KEY_VALS_FK1` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PARTITION_PARAMS` (
                                                  `PART_ID` bigint(20) NOT NULL,
    `PARAM_KEY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PARAM_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`PART_ID`,`PARAM_KEY`),
    KEY `PARTITION_PARAMS_N49` (`PART_ID`),
    CONSTRAINT `PARTITION_PARAMS_FK1` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PART_COL_PRIVS` (
                                                `PART_COLUMN_GRANT_ID` bigint(20) NOT NULL,
    `COLUMN_NAME` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `GRANT_OPTION` smallint(6) NOT NULL,
    `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PART_ID` bigint(20) DEFAULT NULL,
    `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PART_COL_PRIV` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`PART_COLUMN_GRANT_ID`),
    KEY `PART_COL_PRIVS_N49` (`PART_ID`),
    KEY `PARTITIONCOLUMNPRIVILEGEINDEX` (`PART_ID`,`COLUMN_NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`PART_COL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`),
    CONSTRAINT `PART_COL_PRIVS_FK1` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PART_PRIVS` (
                                            `PART_GRANT_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `GRANT_OPTION` smallint(6) NOT NULL,
    `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PART_ID` bigint(20) DEFAULT NULL,
    `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PART_PRIV` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`PART_GRANT_ID`),
    KEY `PARTPRIVILEGEINDEX` (`PART_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`PART_PRIV`,`GRANTOR`,`GRANTOR_TYPE`),
    KEY `PART_PRIVS_N49` (`PART_ID`),
    CONSTRAINT `PART_PRIVS_FK1` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `ROLES` (
                                       `ROLE_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `OWNER_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `ROLE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`ROLE_ID`),
    UNIQUE KEY `ROLEENTITYINDEX` (`ROLE_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `ROLE_MAP` (
                                          `ROLE_GRANT_ID` bigint(20) NOT NULL,
    `ADD_TIME` int(11) NOT NULL,
    `GRANT_OPTION` smallint(6) NOT NULL,
    `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `ROLE_ID` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`ROLE_GRANT_ID`),
    UNIQUE KEY `USERROLEMAPINDEX` (`PRINCIPAL_NAME`,`ROLE_ID`,`GRANTOR`,`GRANTOR_TYPE`),
    KEY `ROLE_MAP_N49` (`ROLE_ID`),
    CONSTRAINT `ROLE_MAP_FK1` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ROLE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SDS` (
                                     `SD_ID` bigint(20) NOT NULL,
    `CD_ID` bigint(20) DEFAULT NULL,
    `INPUT_FORMAT` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `IS_COMPRESSED` bit(1) NOT NULL,
    `IS_STOREDASSUBDIRECTORIES` bit(1) NOT NULL,
    `LOCATION` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `NUM_BUCKETS` int(11) NOT NULL,
    `OUTPUT_FORMAT` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `SERDE_ID` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`SD_ID`),
    KEY `SDS_N49` (`SERDE_ID`),
    KEY `SDS_N50` (`CD_ID`),
    CONSTRAINT `SDS_FK1` FOREIGN KEY (`SERDE_ID`) REFERENCES `SERDES` (`SERDE_ID`),
    CONSTRAINT `SDS_FK2` FOREIGN KEY (`CD_ID`) REFERENCES `CDS` (`CD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SD_PARAMS` (
                                           `SD_ID` bigint(20) NOT NULL,
    `PARAM_KEY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PARAM_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`SD_ID`,`PARAM_KEY`),
    KEY `SD_PARAMS_N49` (`SD_ID`),
    CONSTRAINT `SD_PARAMS_FK1` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SEQUENCE_TABLE` (
                                                `SEQUENCE_NAME` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `NEXT_VAL` bigint(20) NOT NULL,
    PRIMARY KEY (`SEQUENCE_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SERDES` (
                                        `SERDE_ID` bigint(20) NOT NULL,
    `NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `SLIB` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`SERDE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SERDE_PARAMS` (
                                              `SERDE_ID` bigint(20) NOT NULL,
    `PARAM_KEY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PARAM_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`SERDE_ID`,`PARAM_KEY`),
    KEY `SERDE_PARAMS_N49` (`SERDE_ID`),
    CONSTRAINT `SERDE_PARAMS_FK1` FOREIGN KEY (`SERDE_ID`) REFERENCES `SERDES` (`SERDE_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SKEWED_COL_NAMES` (
                                                  `SD_ID` bigint(20) NOT NULL,
    `SKEWED_COL_NAME` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`SD_ID`,`INTEGER_IDX`),
    KEY `SKEWED_COL_NAMES_N49` (`SD_ID`),
    CONSTRAINT `SKEWED_COL_NAMES_FK1` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SKEWED_COL_VALUE_LOC_MAP` (
                                                          `SD_ID` bigint(20) NOT NULL,
    `STRING_LIST_ID_KID` bigint(20) NOT NULL,
    `LOCATION` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`SD_ID`,`STRING_LIST_ID_KID`),
    KEY `SKEWED_COL_VALUE_LOC_MAP_N49` (`STRING_LIST_ID_KID`),
    KEY `SKEWED_COL_VALUE_LOC_MAP_N50` (`SD_ID`),
    CONSTRAINT `SKEWED_COL_VALUE_LOC_MAP_FK2` FOREIGN KEY (`STRING_LIST_ID_KID`) REFERENCES `SKEWED_STRING_LIST` (`STRING_LIST_ID`),
    CONSTRAINT `SKEWED_COL_VALUE_LOC_MAP_FK1` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SKEWED_STRING_LIST` (
                                                    `STRING_LIST_ID` bigint(20) NOT NULL,
    PRIMARY KEY (`STRING_LIST_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SKEWED_STRING_LIST_VALUES` (
                                                           `STRING_LIST_ID` bigint(20) NOT NULL,
    `STRING_LIST_VALUE` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`STRING_LIST_ID`,`INTEGER_IDX`),
    KEY `SKEWED_STRING_LIST_VALUES_N49` (`STRING_LIST_ID`),
    CONSTRAINT `SKEWED_STRING_LIST_VALUES_FK1` FOREIGN KEY (`STRING_LIST_ID`) REFERENCES `SKEWED_STRING_LIST` (`STRING_LIST_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SKEWED_VALUES` (
                                               `SD_ID_OID` bigint(20) NOT NULL,
    `STRING_LIST_ID_EID` bigint(20) NOT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`SD_ID_OID`,`INTEGER_IDX`),
    KEY `SKEWED_VALUES_N50` (`SD_ID_OID`),
    KEY `SKEWED_VALUES_N49` (`STRING_LIST_ID_EID`),
    CONSTRAINT `SKEWED_VALUES_FK2` FOREIGN KEY (`STRING_LIST_ID_EID`) REFERENCES `SKEWED_STRING_LIST` (`STRING_LIST_ID`),
    CONSTRAINT `SKEWED_VALUES_FK1` FOREIGN KEY (`SD_ID_OID`) REFERENCES `SDS` (`SD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SORT_COLS` (
                                           `SD_ID` bigint(20) NOT NULL,
    `COLUMN_NAME` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `ORDER` int(11) NOT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`SD_ID`,`INTEGER_IDX`),
    KEY `SORT_COLS_N49` (`SD_ID`),
    CONSTRAINT `SORT_COLS_FK1` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TABLE_PARAMS` (
                                              `TBL_ID` bigint(20) NOT NULL,
    `PARAM_KEY` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PARAM_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`TBL_ID`,`PARAM_KEY`),
    KEY `TABLE_PARAMS_N49` (`TBL_ID`),
    CONSTRAINT `TABLE_PARAMS_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TBLS` (
                                      `TBL_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `DB_ID` bigint(20) DEFAULT NULL,
    `LAST_ACCESS_TIME` int(11) NOT NULL,
    `OWNER` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `RETENTION` int(11) NOT NULL,
    `SD_ID` bigint(20) DEFAULT NULL,
    `TBL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TBL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `VIEW_EXPANDED_TEXT` mediumtext,
    `VIEW_ORIGINAL_TEXT` mediumtext,
    PRIMARY KEY (`TBL_ID`),
    UNIQUE KEY `UNIQUETABLE` (`TBL_NAME`,`DB_ID`),
    KEY `TBLS_N50` (`SD_ID`),
    KEY `TBLS_N49` (`DB_ID`),
    CONSTRAINT `TBLS_FK1` FOREIGN KEY (`SD_ID`) REFERENCES `SDS` (`SD_ID`),
    CONSTRAINT `TBLS_FK2` FOREIGN KEY (`DB_ID`) REFERENCES `DBS` (`DB_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TBL_COL_PRIVS` (
                                               `TBL_COLUMN_GRANT_ID` bigint(20) NOT NULL,
    `COLUMN_NAME` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `GRANT_OPTION` smallint(6) NOT NULL,
    `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TBL_COL_PRIV` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TBL_ID` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`TBL_COLUMN_GRANT_ID`),
    KEY `TABLECOLUMNPRIVILEGEINDEX` (`TBL_ID`,`COLUMN_NAME`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`TBL_COL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`),
    KEY `TBL_COL_PRIVS_N49` (`TBL_ID`),
    CONSTRAINT `TBL_COL_PRIVS_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TBL_PRIVS` (
                                           `TBL_GRANT_ID` bigint(20) NOT NULL,
    `CREATE_TIME` int(11) NOT NULL,
    `GRANT_OPTION` smallint(6) NOT NULL,
    `GRANTOR` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `GRANTOR_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRINCIPAL_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TBL_PRIV` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TBL_ID` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`TBL_GRANT_ID`),
    KEY `TBL_PRIVS_N49` (`TBL_ID`),
    KEY `TABLEPRIVILEGEINDEX` (`TBL_ID`,`PRINCIPAL_NAME`,`PRINCIPAL_TYPE`,`TBL_PRIV`,`GRANTOR`,`GRANTOR_TYPE`),
    CONSTRAINT `TBL_PRIVS_FK1` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TAB_COL_STATS` (
                                               `CS_ID` bigint(20) NOT NULL,
    `DB_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `TABLE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `COLUMN_NAME` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `COLUMN_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `TBL_ID` bigint(20) NOT NULL,
    `LONG_LOW_VALUE` bigint(20),
    `LONG_HIGH_VALUE` bigint(20),
    `DOUBLE_HIGH_VALUE` double(53,4),
    `DOUBLE_LOW_VALUE` double(53,4),
    `BIG_DECIMAL_LOW_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin,
    `BIG_DECIMAL_HIGH_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin,
    `NUM_NULLS` bigint(20) NOT NULL,
    `NUM_DISTINCTS` bigint(20),
    `AVG_COL_LEN` double(53,4),
    `MAX_COL_LEN` bigint(20),
    `NUM_TRUES` bigint(20),
    `NUM_FALSES` bigint(20),
    `LAST_ANALYZED` bigint(20) NOT NULL,
    PRIMARY KEY (`CS_ID`),
    CONSTRAINT `TAB_COL_STATS_FK` FOREIGN KEY (`TBL_ID`) REFERENCES `TBLS` (`TBL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PART_COL_STATS` (
                                                `CS_ID` bigint(20) NOT NULL,
    `DB_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `TABLE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PARTITION_NAME` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `COLUMN_NAME` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `COLUMN_TYPE` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `PART_ID` bigint(20) NOT NULL,
    `LONG_LOW_VALUE` bigint(20),
    `LONG_HIGH_VALUE` bigint(20),
    `DOUBLE_HIGH_VALUE` double(53,4),
    `DOUBLE_LOW_VALUE` double(53,4),
    `BIG_DECIMAL_LOW_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin,
    `BIG_DECIMAL_HIGH_VALUE` varchar(4000) CHARACTER SET latin1 COLLATE latin1_bin,
    `NUM_NULLS` bigint(20) NOT NULL,
    `NUM_DISTINCTS` bigint(20),
    `AVG_COL_LEN` double(53,4),
    `MAX_COL_LEN` bigint(20),
    `NUM_TRUES` bigint(20),
    `NUM_FALSES` bigint(20),
    `LAST_ANALYZED` bigint(20) NOT NULL,
    PRIMARY KEY (`CS_ID`),
    CONSTRAINT `PART_COL_STATS_FK` FOREIGN KEY (`PART_ID`) REFERENCES `PARTITIONS` (`PART_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

# CREATE INDEX PCS_STATS_IDX ON PART_COL_STATS (DB_NAME,TABLE_NAME,COLUMN_NAME,PARTITION_NAME) USING BTREE;
CREATE INDEX PCS_STATS_IDX
    ON PART_COL_STATS (
                       DB_NAME(128),
                       TABLE_NAME(128),
                       COLUMN_NAME(128),
                       PARTITION_NAME(128)
        ) USING BTREE;

CREATE TABLE IF NOT EXISTS `TYPES` (
                                       `TYPES_ID` bigint(20) NOT NULL,
    `TYPE_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TYPE1` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `TYPE2` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    PRIMARY KEY (`TYPES_ID`),
    UNIQUE KEY `UNIQUE_TYPE` (`TYPE_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TYPE_FIELDS` (
                                             `TYPE_NAME` bigint(20) NOT NULL,
    `COMMENT` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `FIELD_NAME` varchar(128) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `FIELD_TYPE` varchar(767) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `INTEGER_IDX` int(11) NOT NULL,
    PRIMARY KEY (`TYPE_NAME`,`FIELD_NAME`),
    KEY `TYPE_FIELDS_N49` (`TYPE_NAME`),
    CONSTRAINT `TYPE_FIELDS_FK1` FOREIGN KEY (`TYPE_NAME`) REFERENCES `TYPES` (`TYPES_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `MASTER_KEYS`
(
    `KEY_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MASTER_KEY` VARCHAR(767) BINARY NULL,
    PRIMARY KEY (`KEY_ID`)
    ) ENGINE=INNODB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `DELEGATION_TOKENS`
(
    `TOKEN_IDENT` VARCHAR(767) BINARY NOT NULL,
    `TOKEN` VARCHAR(767) BINARY NULL,
    PRIMARY KEY (`TOKEN_IDENT`)
    ) ENGINE=INNODB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `VERSION` (
                                         `VER_ID` BIGINT NOT NULL,
                                         `SCHEMA_VERSION` VARCHAR(127) NOT NULL,
    `VERSION_COMMENT` VARCHAR(255),
    PRIMARY KEY (`VER_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `FUNCS` (
                                       `FUNC_ID` BIGINT(20) NOT NULL,
    `CLASS_NAME` VARCHAR(4000) CHARACTER SET latin1 COLLATE latin1_bin,
    `CREATE_TIME` INT(11) NOT NULL,
    `DB_ID` BIGINT(20),
    `FUNC_NAME` VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_bin,
    `FUNC_TYPE` INT(11) NOT NULL,
    `OWNER_NAME` VARCHAR(128) CHARACTER SET latin1 COLLATE latin1_bin,
    `OWNER_TYPE` VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_bin,
    PRIMARY KEY (`FUNC_ID`),
    UNIQUE KEY `UNIQUEFUNCTION` (`FUNC_NAME`, `DB_ID`),
    KEY `FUNCS_N49` (`DB_ID`),
    CONSTRAINT `FUNCS_FK1` FOREIGN KEY (`DB_ID`) REFERENCES `DBS` (`DB_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `FUNC_RU` (
                                         `FUNC_ID` BIGINT(20) NOT NULL,
    `RESOURCE_TYPE` INT(11) NOT NULL,
    `RESOURCE_URI` VARCHAR(4000) CHARACTER SET latin1 COLLATE latin1_bin,
    `INTEGER_IDX` INT(11) NOT NULL,
    PRIMARY KEY (`FUNC_ID`, `INTEGER_IDX`),
    CONSTRAINT `FUNC_RU_FK1` FOREIGN KEY (`FUNC_ID`) REFERENCES `FUNCS` (`FUNC_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `NOTIFICATION_LOG`
(
    `NL_ID` BIGINT(20) NOT NULL,
    `EVENT_ID` BIGINT(20) NOT NULL,
    `EVENT_TIME` INT(11) NOT NULL,
    `EVENT_TYPE` varchar(32) NOT NULL,
    `DB_NAME` varchar(128),
    `TBL_NAME` varchar(128),
    `MESSAGE` mediumtext,
    PRIMARY KEY (`NL_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `NOTIFICATION_SEQUENCE`
(
    `NNI_ID` BIGINT(20) NOT NULL,
    `NEXT_EVENT_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY (`NNI_ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `KEY_CONSTRAINTS`
(
    `CHILD_CD_ID` BIGINT,
    `CHILD_INTEGER_IDX` INT(11),
    `CHILD_TBL_ID` BIGINT,
    `PARENT_CD_ID` BIGINT NOT NULL,
    `PARENT_INTEGER_IDX` INT(11) NOT NULL,
    `PARENT_TBL_ID` BIGINT NOT NULL,
    `POSITION` BIGINT NOT NULL,
    `CONSTRAINT_NAME` VARCHAR(400) NOT NULL,
    `CONSTRAINT_TYPE` SMALLINT(6)  NOT NULL,
    `UPDATE_RULE` SMALLINT(6),
    `DELETE_RULE` SMALLINT(6),
    `ENABLE_VALIDATE_RELY` SMALLINT(6) NOT NULL,
    PRIMARY KEY (`CONSTRAINT_NAME`, `POSITION`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE INDEX `CONSTRAINTS_PARENT_TABLE_ID_INDEX` ON KEY_CONSTRAINTS (`PARENT_TBL_ID`) USING BTREE;


INSERT INTO VERSION (VER_ID, SCHEMA_VERSION, VERSION_COMMENT) VALUES (1, '2.1.0', 'Hive release version 2.1.0');
